ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CAPTAIN';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POLL_OPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POLL_CLOSING_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POLL_NEAR_FULL';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POLL_PROMOTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MATCH_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MATCH_UPDATED';
